name: Merge

on:
  workflow_dispatch:

jobs:
  run-ranker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch --all
          git checkout result
          git pull

          git checkout main -- package.json || true
          git checkout main -- tsconfig.json || true
          git checkout main -- bun.lockb || true
          git checkout main -- src || true

      - uses: oven-sh/setup-bun@v2
      - run: |
          bun i -p
          bun run merge

      - run: |
          mkdir tmp
          mv merged_global.json tmp/
          mv merged_kr.json tmp/

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          publish_dir: tmp
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          enable_jekyll: true
          keep_files: true
          publish_branch: result
