name: Daily

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  run-ranker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch --all
          git checkout main
          git pull

          git checkout result -- merged_global.json
          git checkout result -- merged_kr.json

      - uses: oven-sh/setup-bun@v2
      - run: |
          bun i -p
          bun run start
          bun run merge

      - run: |
          mkdir tmp
          mv $(date +'%Y-%m-%d') tmp/
          mv merged_global.json tmp/
          mv merged_kr.json tmp/

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          publish_dir: tmp
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          enable_jekyll: true
          keep_files: true
          publish_branch: result
